steps:
  - name: 'gcr.io/glass-world-245718/composer'
    args: ['install']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'containers-test-symfony', '.']
    
tags: ['mtgbracket', 'api']