steps:
  - name: 'gcr.io/$PROJECT_ID/composer'
    args: ['install']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/containers-test-symfony:0.0.2', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/containers-test-symfony']
    
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/symfony-test', 'containers-test-symfony-sha256=gcr.io/$PROJECT_ID/containers-test-symfony:0.0.2']
    env:
        - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
        - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
tags: ['mtgbracket', 'api']
#images: ['gcr.io/glass-world-245718/containers-test-symfony']